guidance_scale: 7 # weight of the text guidance
guidance_scale_y: 1
log_iter_step: 5
ddim_eta: 0.1
init_strategy: 'y_noise' #'noise' #'y', 'y_noise'
t_start: 1000
num_inference_steps: 20 # for latent_dps it is beneficial to take a large number of steps
ada_guidance_y: False
stop_guidance_t: 0 # stop y guidance when t<stop_guidance_t (set to 0 to disable)